apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: testdonet0506aaa
  janus-idp.io/tekton: testdonet0506aaa
  backstage.io/kubernetes-id: testdonet0506aaa
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: testdonet0506aaa
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
