apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: testdonet0506aaa
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: testdonet0506aaa 
  name: testdonet0506aaa
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: testdonet0506aaa 
